import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

/* ============================================================
   Enums
   ============================================================ */

export const orgTypeEnum = pgEnum("org_type", ["research", "clinic"]);
export const memberRoleEnum = pgEnum("member_role", ["owner", "analyst", "clinician", "viewer"]);
export const sexEnum = pgEnum("sex", ["female", "male", "unspecified"]);

export const platformEnum = pgEnum("platform", [
  "methylation_450k",
  "methylation_epic",
  "methylation_epic_v2",
  "chem_panel",
  "olink",
  "telomere",
]);

export const qcStatusEnum = pgEnum("qc_status", ["pending", "passed", "warned", "failed"]);
export const parseStatusEnum = pgEnum("parse_status", ["pending", "parsed", "failed"]);

export const interventionCategoryEnum = pgEnum("intervention_category", [
  "reprogramming",
  "senolytic",
  "mtor_modulating",
  "nutrition",
  "exercise",
  "other",
]);

export const evidenceSourceEnum = pgEnum("evidence_source", ["org_entered", "self_reported"]);

/* ============================================================
   Tenancy
   ============================================================ */

export const organizations = pgTable("organizations", {
  id: uuid("id").primaryKey().defaultRandom(),
  /** External auth provider organization id (Clerk org id). */
  externalId: text("external_id").notNull().unique(),
  name: text("name").notNull(),
  type: orgTypeEnum("type").notNull().default("research"),
  /**
   * Master switch for identifiable data. False everywhere in v1. Gates the
   * identity columns on `subjects`, export behavior, and retention policy.
   * Flipping this per-organization is the HIPAA upgrade path.
   */
  phiEnabled: boolean("phi_enabled").notNull().default(false),
  /** Storage/processing region pin, e.g. "us-east-1". */
  region: text("region").notNull().default("us-east-1"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  externalId: text("external_id").notNull().unique(),
  email: text("email").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const memberships = pgTable(
  "memberships",
  {
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    role: memberRoleEnum("role").notNull().default("viewer"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.orgId, t.userId] })],
);

/* ============================================================
   Subjects — the PHI boundary
   ============================================================
   Identity lives here and nowhere else. Every other table references
   subject_id only. Adding identifiable fields later touches this table and
   one access policy, not the whole schema.
   ============================================================ */

export const subjects = pgTable(
  "subjects",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    /** The customer's own pseudonymous code. Never generated by us. */
    externalRef: text("external_ref").notNull(),
    /** Quasi-identifiers that clock models genuinely require. */
    chronologicalAge: numeric("chronological_age", { precision: 5, scale: 2 }),
    sex: sexEnum("sex").notNull().default("unspecified"),
    /** Free-text cell line / model identifier for research organizations. */
    modelSystem: text("model_system"),
    /**
     * Identifiable fields. Writes are rejected unless the owning
     * organization has phi_enabled = true (enforced by trigger, see rls.sql).
     */
    displayName: text("display_name"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("subjects_org_ref_idx").on(t.orgId, t.externalRef),
    index("subjects_org_idx").on(t.orgId),
  ],
);

/* ============================================================
   Samples and files
   ============================================================ */

export const samples = pgTable(
  "samples",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    subjectId: uuid("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    collectedAt: timestamp("collected_at", { withTimezone: true }).notNull(),
    tissue: text("tissue").notNull().default("whole_blood"),
    platform: platformEnum("platform").notNull(),
    sourceLab: text("source_lab"),
    qcStatus: qcStatusEnum("qc_status").notNull().default("pending"),
    qcReport: jsonb("qc_report"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("samples_subject_idx").on(t.subjectId, t.collectedAt),
    index("samples_org_idx").on(t.orgId),
  ],
);

export const dataFiles = pgTable(
  "data_files",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    sampleId: uuid("sample_id").references(() => samples.id, { onDelete: "cascade" }),
    objectKey: text("object_key").notNull(),
    sha256: text("sha256").notNull(),
    byteSize: integer("byte_size").notNull(),
    kind: text("kind").notNull(),
    originalFilename: text("original_filename").notNull(),
    parseStatus: parseStatusEnum("parse_status").notNull().default("pending"),
    parseErrors: jsonb("parse_errors"),
    uploadedAt: timestamp("uploaded_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("data_files_org_idx").on(t.orgId), uniqueIndex("data_files_key_idx").on(t.objectKey)],
);

/* ============================================================
   Measurements
   ============================================================ */

/** Long-form store for panel and proteomic analytes. */
export const measurements = pgTable(
  "measurements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    sampleId: uuid("sample_id")
      .notNull()
      .references(() => samples.id, { onDelete: "cascade" }),
    analyteKey: text("analyte_key").notNull(),
    value: numeric("value", { precision: 18, scale: 6 }).notNull(),
    unit: text("unit").notNull(),
    belowLoq: boolean("below_loq").notNull().default(false),
  },
  (t) => [
    uniqueIndex("measurements_sample_analyte_idx").on(t.sampleId, t.analyteKey),
    index("measurements_org_idx").on(t.orgId),
  ],
);

/**
 * Only the CpG probes required by registered clocks. The complete normalized
 * matrix stays in object storage as Parquet, so this table holds thousands of
 * rows per sample rather than ~850k.
 */
export const probeFeatures = pgTable(
  "probe_features",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    sampleId: uuid("sample_id")
      .notNull()
      .references(() => samples.id, { onDelete: "cascade" }),
    probeId: text("probe_id").notNull(),
    beta: numeric("beta", { precision: 10, scale: 8 }).notNull(),
    imputed: boolean("imputed").notNull().default(false),
  },
  (t) => [
    uniqueIndex("probe_features_sample_probe_idx").on(t.sampleId, t.probeId),
    index("probe_features_org_idx").on(t.orgId),
  ],
);

/** Pointer to the full normalized matrix in object storage. */
export const featureMatrices = pgTable("feature_matrices", {
  id: uuid("id").primaryKey().defaultRandom(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id, { onDelete: "cascade" }),
  sampleId: uuid("sample_id")
    .notNull()
    .references(() => samples.id, { onDelete: "cascade" }),
  objectKey: text("object_key").notNull(),
  probeCount: integer("probe_count").notNull(),
  pipelineVersion: text("pipeline_version").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/* ============================================================
   Results
   ============================================================ */

export const clockResults = pgTable(
  "clock_results",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    sampleId: uuid("sample_id")
      .notNull()
      .references(() => samples.id, { onDelete: "cascade" }),
    clockId: text("clock_id").notNull(),
    clockVersion: text("clock_version").notNull(),
    pipelineVersion: text("pipeline_version").notNull(),
    value: numeric("value", { precision: 10, scale: 4 }),
    ciLow: numeric("ci_low", { precision: 10, scale: 4 }),
    ciHigh: numeric("ci_high", { precision: 10, scale: 4 }),
    probesUsed: integer("probes_used").notNull(),
    probesImputed: integer("probes_imputed").notNull(),
    /** Set when the pipeline refused to emit a value. */
    refusedReason: text("refused_reason"),
    qcFlags: jsonb("qc_flags"),
    computedAt: timestamp("computed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("clock_results_sample_clock_idx").on(t.sampleId, t.clockId, t.clockVersion),
    index("clock_results_org_idx").on(t.orgId),
  ],
);

export const hallmarkScores = pgTable(
  "hallmark_scores",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    sampleId: uuid("sample_id")
      .notNull()
      .references(() => samples.id, { onDelete: "cascade" }),
    axisKey: text("axis_key").notNull(),
    /** Null when computable = false. Never fabricate a score. */
    score: numeric("score", { precision: 10, scale: 4 }),
    percentile: numeric("percentile", { precision: 6, scale: 3 }),
    computable: boolean("computable").notNull(),
    confidence: text("confidence").notNull(),
    inputsUsed: jsonb("inputs_used").notNull(),
    inputsMissing: jsonb("inputs_missing").notNull(),
    pipelineVersion: text("pipeline_version").notNull(),
    computedAt: timestamp("computed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("hallmark_scores_sample_axis_idx").on(t.sampleId, t.axisKey),
    index("hallmark_scores_org_idx").on(t.orgId),
  ],
);

/* ============================================================
   Interventions and episodes — the dataset asset
   ============================================================ */

export const interventions = pgTable(
  "interventions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    subjectId: uuid("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    category: interventionCategoryEnum("category").notNull(),
    agent: text("agent").notNull(),
    dose: text("dose"),
    route: text("route"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
    physicianSupervised: boolean("physician_supervised").notNull().default(false),
    evidenceSource: evidenceSourceEnum("evidence_source").notNull().default("org_entered"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("interventions_subject_idx").on(t.subjectId, t.startedAt),
    index("interventions_org_idx").on(t.orgId),
  ],
);

/**
 * Binds a pre-sample, a set of interventions, and a post-sample into one
 * comparable unit. This is the row that makes the dataset queryable.
 */
export const episodes = pgTable(
  "episodes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    subjectId: uuid("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    preSampleId: uuid("pre_sample_id")
      .notNull()
      .references(() => samples.id, { onDelete: "restrict" }),
    postSampleId: uuid("post_sample_id")
      .notNull()
      .references(() => samples.id, { onDelete: "restrict" }),
    label: text("label"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("episodes_samples_idx").on(t.preSampleId, t.postSampleId),
    index("episodes_org_idx").on(t.orgId),
  ],
);

export const episodeInterventions = pgTable(
  "episode_interventions",
  {
    episodeId: uuid("episode_id")
      .notNull()
      .references(() => episodes.id, { onDelete: "cascade" }),
    interventionId: uuid("intervention_id")
      .notNull()
      .references(() => interventions.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.episodeId, t.interventionId] })],
);

export const deltaResults = pgTable(
  "delta_results",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    episodeId: uuid("episode_id")
      .notNull()
      .references(() => episodes.id, { onDelete: "cascade" }),
    metricKey: text("metric_key").notNull(),
    preValue: numeric("pre_value", { precision: 12, scale: 4 }).notNull(),
    postValue: numeric("post_value", { precision: 12, scale: 4 }).notNull(),
    delta: numeric("delta", { precision: 12, scale: 4 }).notNull(),
    mdc: numeric("mdc", { precision: 12, scale: 4 }).notNull(),
    exceedsMdc: boolean("exceeds_mdc").notNull(),
    pipelineVersion: text("pipeline_version").notNull(),
    computedAt: timestamp("computed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("delta_results_episode_metric_idx").on(t.episodeId, t.metricKey),
    index("delta_results_org_idx").on(t.orgId),
  ],
);

/* ============================================================
   Reports — immutable once issued
   ============================================================ */

export const reports = pgTable(
  "reports",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    subjectId: uuid("subject_id")
      .notNull()
      .references(() => subjects.id, { onDelete: "cascade" }),
    sampleId: uuid("sample_id")
      .notNull()
      .references(() => samples.id, { onDelete: "restrict" }),
    episodeId: uuid("episode_id").references(() => episodes.id, { onDelete: "set null" }),
    objectKey: text("object_key"),
    templateVersion: text("template_version").notNull(),
    disclaimerVersion: text("disclaimer_version").notNull(),
    clockVersions: jsonb("clock_versions").notNull(),
    pipelineVersion: text("pipeline_version").notNull(),
    /** Snapshot of everything rendered, so the report survives data edits. */
    payload: jsonb("payload").notNull(),
    generatedBy: uuid("generated_by").references(() => users.id, { onDelete: "set null" }),
    generatedAt: timestamp("generated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("reports_org_idx").on(t.orgId), index("reports_subject_idx").on(t.subjectId)],
);

/* ============================================================
   Audit + metering
   ============================================================ */

export const auditEvents = pgTable(
  "audit_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id").references(() => organizations.id, { onDelete: "set null" }),
    actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    resourceType: text("resource_type").notNull(),
    resourceId: text("resource_id"),
    /** Never store subject identifiers or analyte values here. */
    metadata: jsonb("metadata"),
    ip: text("ip"),
    userAgent: text("user_agent"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("audit_events_org_time_idx").on(t.orgId, t.occurredAt)],
);

export const usageEvents = pgTable(
  "usage_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    quantity: integer("quantity").notNull().default(1),
    /** Stripe usage record id once reported, null while pending. */
    reportedRef: text("reported_ref"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("usage_events_org_time_idx").on(t.orgId, t.occurredAt)],
);

export const subscriptions = pgTable("subscriptions", {
  orgId: uuid("org_id")
    .primaryKey()
    .references(() => organizations.id, { onDelete: "cascade" }),
  stripeCustomerId: text("stripe_customer_id").notNull(),
  stripeSubscriptionId: text("stripe_subscription_id"),
  plan: text("plan").notNull().default("pilot"),
  seats: integer("seats").notNull().default(1),
  reportCredits: integer("report_credits").notNull().default(0),
  status: text("status").notNull().default("trialing"),
  currentPeriodEnd: timestamp("current_period_end", { withTimezone: true }),
});
